-- SQL: crear tabla products y políticas RLS mínimas
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  quantity int not null default 0,
  created_at timestamptz default now()
);

-- Habilitar RLS
alter table public.products enable row level security;

-- Permitir SELECT público (opcional). Si quieres que SOLO usuarios autenticados lean,
-- elimina o comenta esta policy.
create policy "public_select_products"
  on public.products
  for select
  to anon
  using (true);

-- Policies para que SOLO el admin (por email) pueda insertar/actualizar/borrar
-- Reemplaza 'jsnowoliv@gmail.com' si más adelante deseas cambiar el admin
create policy "admin_insert" on public.products
  for insert
  to authenticated
  with check (auth.jwt() ->> 'email' = 'jsnowoliv@gmail.com');

create policy "admin_update" on public.products
  for update
  to authenticated
  using (auth.jwt() ->> 'email' = 'jsnowoliv@gmail.com')
  with check (auth.jwt() ->> 'email' = 'jsnowoliv@gmail.com');

create policy "admin_delete" on public.products
  for delete
  to authenticated
  using (auth.jwt() ->> 'email' = 'jsnowoliv@gmail.com');
